"""empty message

Revision ID: d1690e86952e
Revises: 0344aceeeb4d
Create Date: 2024-03-03 14:45:51.049142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1690e86952e'
down_revision: Union[str, None] = '0344aceeeb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_blocked', sa.DateTime(), nullable=False),
    sa.Column('end_date_block', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banned_users')
    # ### end Alembic commands ###
