from .tokens import BODY_USER_LOGIN_EXAMPLE
from .users import BODY_USER_CREATE_EXAMPLE, BODY_USER_UPDATE_EXAMPLE

__all__ = ('BODY_USER_LOGIN_EXAMPLE', 'BODY_USER_CREATE_EXAMPLE',
           'BODY_USER_UPDATE_EXAMPLE')
