"""empty message

Revision ID: 4fe06c316f93
Revises: 761ad193bdbe
Create Date: 2023-12-31 21:36:18.476806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe06c316f93'
down_revision: Union[str, None] = '761ad193bdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'created_at')
    # ### end Alembic commands ###
