name: Check Pull Requests

on:
  push:
    branches:
      - dev
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.2.4
        ports:
          - 6379:6379

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -e .[dev]

      - name: Run tests
        run: |
          pytest

  send_message_tests:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Tests success!
